[project]
name = "garmin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "garmindb>=3.6.2",
    "psycopg[binary,pool]>=3.2.11",
]
