[project]
name = "airflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=3.1.1",
    "apache-airflow-providers-docker>=4.4.4",
    "psycopg>=3.2.13",
    "structlog<25.5.0",
]
