[project]
name = "vis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "altair[all]>=6.0.0",
    "dotenv>=0.9.9",
    "pandas>=2.3.3",
    "psycopg[binary,pool]>=3.2.11",
]
